- name: "nisd_initialization_and_startup"
  hosts: localhost
  connection: local
  vars:
    recipe_name: "nisd_initialization_and_startup"
    parent: None
    nisd_root_keys:
              - "/nisd_root_entry/0/uuid"
              - "/nisd_root_entry/0/instance-uuid"
              - "/nisd_root_entry/0/status"
              - "/nisd_root_entry/0/num-reserved-pblks"
              - "/nisd_root_entry/0/num-pblks"
              - "/nisd_root_entry/0/vblks-written"
              - "/nisd_root_entry/0/num-pblks-used"
              - "/nisd_root_entry/0/num-reserved-pblks-used"
    nisd_chunk_keys:
              - "/nisd_chunks/0/vdev-uuid"
              - "/nisd_chunks/0/number"
              - "/nisd_chunks/0/num-data-pblks"
              - "/nisd_chunks/0/num-meta-pblks"
              - "/nisd_chunks/0/num-reserved-meta-pblks"
              - "/nisd_chunks/0/metablock-seqno"
              - "/nisd_chunks/0/vblks-read"
              - "/nisd_chunks/0/num-cme"
              - "/nisd_chunks/0/ref-cnt"
              - "/nisd_chunks/0/merge-info/shallow-cnt"
              - "/nisd_chunks/0/merge-info/full-status"

  tasks:
  - block:

     - name: "Prepare port range file."
       set_fact: nisdPortRangeCreation="{{lookup('niova_raftconfig', "{{ app_type }}", 0)}}"

     - name: "{{ recipe_name }}: Start niova-lookout process."
       vars:
         input_param: {
                 'uport' : '{{ (srv_port | int) + 20 + item }}'
                 }
       set_fact:
         get_lookout: "{{ get_lookout | default([]) + [lookup('controlplane', 'niova-lookout', input_param)] }}"
       loop: "{{ range(0, nlookouts | int) }}"

     - name: "{{ recipe_name }}: Starting controlplane_client to start prometheus."
       vars:
         input_param: {
                  'Hport': ''
                  }
       debug:
         msg: "{{ lookup('controlplane', 'prometheus', input_param) }}"

     - name: "{{ recipe_name }}: Start niova-block-ctl process."
       vars:
          input_param: {
             'nisd_dev_size': '68719476736',
             'lookout_uuid': '{{ get_lookout[0] }}',
             'alt_name': 'nisd{{item}}'
              }
       set_fact:
         get_nisd: "{{ get_nisd | default([]) + [lookup('nisd_handler', 'niova-block-ctl', input_param)] }}"
       loop: "{{ range(0, nnisds | int) }}"
       no_log: false

     - name: "{{ recipe_name }}: Start nisd process."
       vars:
          input_param: {
              'nisd_uuid' : '{{ item }}',
              'uport' : '{{ 1053 + (nisd_idx*2) }}',
              'lookout_uuid': '{{ get_lookout[0] }}'
              }
       debug:
         msg: "{{ lookup('nisd_handler', 'nisd', input_param) }}"
       loop: "{{ get_nisd }}"
       loop_control:
         index_var: nisd_idx
       no_log: false

     - pause:
         seconds: 2

     - name: "{{ recipe_name}}: Wait until nisd_root_entry gets updated"
       vars:
         stage: "wait_for_nisd_root_entry"
         lookout_uuid: "{{ get_lookout[0] }}"
       debug:
         msg:
          - "Waiting for nisd to get updated"
          - "{{ lookup('niova_ctlrequest', 'lookup', item, '/nisd_root_entry/0/status', 'nisd', lookout_uuid) }}"
       no_log: false
       until: lookup('niova_ctlrequest', 'lookup', item, '/nisd_root_entry/0/status', 'nisd', lookout_uuid) | dict2items | map(attribute='value') | list | first == "running"
       retries: 60
       delay: 1
       loop: "{{ get_nisd }}"

     - name: "{{ recipe_name }}: Get nisd_root_entry info."
       vars:
          stage: "collect_nisd_root_entry"
          lookout_uuid: "{{ get_lookout[0] }}"
          nisdRootEntryVal: "{{ lookup('niova_ctlrequest', 'lookup', item, nisd_root_keys, 'nisd', lookout_uuid) }}"
       set_fact:
          all_nisd_root_entries: >-
            {{
              all_nisd_root_entries | default([]) +
              [{
                'nisd_uuid': item,
                'entry': nisdRootEntryVal
              }]
            }}
       loop: "{{ get_nisd }}"

     - debug:
         msg: "{{ all_nisd_root_entries }}"

     - name: "{{ recipe_name }}: prepare path to read recipe JSON file."
       vars:
         base_dir: "{{ ClusterInfo | json_query('base_dir_path')}}"
         raft_uuid: "{{ ClusterInfo | json_query('raft_uuid')}}"
       shell: cat "{{base_dir}}"/"{{raft_uuid}}".json
       register: result

     - name: "{{ recipe_name }}: Convert output to JSON format."
       set_fact:
         getRaftProcessDetails: "{{ result.stdout | from_json }}"

     - name: "{{ recipe_name }}: Get the IMG_FILE_NAME."
       set_fact:
         getDeviceFile: "{{ getDeviceFile | default([]) + [getRaftProcessDetails | json_query(jmesquery)] }}"
       vars:
         jmesquery: 'raft_process."{{ item }}".img_file_name'
       loop: "{{ get_nisd }}"

     - debug:
         msg: "{{ getDeviceFile }}"

     - name: "{{ recipe_name }}: Verify nisd_root_entry info."
       vars:
         verifyNisd: "{{ item.entry }}"
         nisd_uuid: "{{ item.nisd_uuid }}"
       debug:
         msg: "{{ verifyNisd }}"
       failed_when: >
         (verifyNisd['/0/uuid'] != nisd_uuid) or
         (verifyNisd['/0/status'] != "running")
       loop: "{{ all_nisd_root_entries }}"

     - name: "{{ recipe_name }}: Get niorq_mgr_root_entry info."
       vars:
         stage: "get_nisd_root_entry"
         nisd_uuid: "{{ item.nisd_uuid }}"
         verifyNisd: "{{ item.entry['/0/num-reserved-pblks'] }}"
         expected_dev_file: "{{ getDeviceFile[ansible_loop.index0] }}"
         nisd_keys:
              - "/niorq_mgr_root_entry/0/uuid"
              - "/niorq_mgr_root_entry/0/dev-path"
              - "/niorq_mgr_root_entry/0/status"
              - "/niorq_mgr_root_entry/0/dev-bytes-read"
              - "/niorq_mgr_root_entry/0/dev-rd-size"
         lookout_uuid: "{{ get_lookout[0] }}"
         niorq_mgr_entry: "{{ lookup('niova_ctlrequest', 'lookup', nisd_uuid, nisd_keys, 'nisd', lookout_uuid) }}"
       debug:
         msg: "Verify niorq_mgr_root_entry info: {{ niorq_mgr_entry }}"
       no_log: false
       until: >
         (niorq_mgr_entry['/0/uuid'] == nisd_uuid) and
         (niorq_mgr_entry['/0/status'] == "running") and
         (niorq_mgr_entry['/0/dev-path'] == expected_dev_file) and
         (niorq_mgr_entry['/0/dev-rd-size']['512'] == 3) and
         (niorq_mgr_entry['/0/dev-rd-size']['16384'] == (verifyNisd | int)) and
         (niorq_mgr_entry['/0/dev-bytes-read'] == ((verifyNisd | int) * 16384) + (3 * 512))
       retries: 10
       delay: 1
       loop: "{{ all_nisd_root_entries }}"
       loop_control:
         extended: true

     - name: "Verify 'tasks' items are idle."
       include_role:
         name: common
         tasks_from: verify_nisd_tasks_parameters
       vars:
         NisdUUID: "{{ nisd_uuid }}"
         LookoutUUID: "{{ get_lookout[0] }}"
       loop: "{{ get_nisd }}"
       loop_control:
         loop_var: nisd_uuid

     - name: "{{ recipe_name }}: Kill the nisd process."
       debug:
         msg:  "{{ lookup('niova_raftprocess', 'kill', item) }}"
       no_log: false
       loop: "{{ get_nisd }}"

     - name: "{{ recipe_name }}: Restart same nisd process."
       vars:
          input_param: {
                  'nisd_uuid' : '{{ item }}',
                  'uport' : '{{ 1053 + (nisd_idx*2) }}',
                  'lookout_uuid': '{{ get_lookout[0] }}'
                  }
       debug:
         msg: "{{ lookup('nisd_handler', 'nisd', input_param) }}"
       no_log: false
       loop: "{{ get_nisd }}"
       loop_control:
         index_var: nisd_idx
       
     - name: "{{ recipe_name }}: Wait for nisd to get updated."
       vars:
         stage: "wait_for_nisd_root_entry"
         lookout_uuid: "{{ get_lookout[0] }}"
       debug:
         msg: "Waiting for nisd to get updated"
       until: lookup('niova_ctlrequest', 'lookup', item, "/nisd_root_entry/0/status", 'nisd', lookout_uuid) | dict2items | map(attribute='value') | list | first == "running"
       retries: 10
       delay: 1
       loop: "{{ get_nisd }}"

     - name: "{{ recipe_name }}: Get nisd_root_entry info after restart."
       vars:
          stage: "afterRestart_nisd_root_entry"
          lookout_uuid: "{{ get_lookout[0] }}"
          nisdRootEntryVal: "{{ lookup('niova_ctlrequest', 'lookup', item, nisd_root_keys, 'nisd', lookout_uuid) }}"
       set_fact:
          aftrRestartNisd: >-
            {{
              aftrRestartNisd | default([]) +
              [{
                'nisd_uuid': item,
                'entry': nisdRootEntryVal
              }]
            }}
       loop: "{{ get_nisd }}"

     - name: "{{ recipe_name }}: Verify nisd_root_entry info after restart."
       vars:
         prev_instance_uuid: "{{ all_nisd_root_entries[idx].entry }}"
         verifyNisd: "{{ aftrRestartNisd[idx].entry }}"
         nisd_uuid: "{{ aftrRestartNisd[idx].nisd_uuid }}"
       debug:
         msg: "Verify nisd root entry values for {{ nisd_uuid }}"
       no_log: True
       failed_when: >
         (verifyNisd['/0/uuid'] != nisd_uuid) or
         (verifyNisd['/0/status'] != "running") or
         (verifyNisd['/0/instance-uuid'] == prev_instance_uuid['/0/instance-uuid'])
       loop: "{{ range(0, aftrRestartNisd | length) | list }}"
       loop_control:
         index_var: idx

     # Get multiple vdev uuids using common task.
     - name: "Get multiple vdev uuids."
       include_role:
        name: common
        tasks_from: get_multiple_vdev_uuids
       loop: "{{ range(0, get_nisd | length) | list }}"

     # Get multiple client uuids using common task.
     - name: "Get multiple client uuids."
       include_role:
        name: common
        tasks_from: get_multiple_client_uuids
       loop: "{{ range(0, get_nisd | length) | list }}"

     - name: "{{ recipe_name }}: Perform some Writes to the NISD."
       vars:
          input_param: {
                 'enable_auth': 0,
                 'cp_mode': 0,
                 'nisd_uuid_to_write' : 'unix:{{ get_nisd[item] }}',
                 'vdev' : '{{ VdevUUIDS[item] }}',
                 'rd_op_ratio' : '0',
                 'random_seed_pt' : '123',
                 'client_uuid' : '{{ ClientUUIDS[item] }}',
                 'request_size_in_bytes' : '32',
                 'queue_depth' : '1',
                 'num_ops' : '50',
                 'integrity_check' : True,
                 'sequential_writes' : False,
                 'blocking_process' : False,
                 'lookout_uuid': '{{ get_lookout[0] }}'
                 }
       set_fact:
          wr_results: "{{ (wr_results | default([])) + [lookup('nisd_handler', 'niova-block-test', input_param) | string] }}"
       loop: "{{ range(0, get_nisd | length) | list }}"

     - name: "{{ recipe_name }}: Show write results."
       debug:
         msg: "Write results: {{ wr_results }}"

     - name: "{{ recipe_name }}: Fail if any write failed."
       debug:
         msg: "One or more niova-block-test writes failed: {{ wr_results }}"
       failed_when: (wr_results | reject('equalto', '0') | list | length) > 0

     - name: "{{ recipe_name }}: Verify nisd_root and nisd_chunk info after writes."
       vars:
         stage: "get_nisd_chunk_after_writes"
         old_num_block_used: "{{ aftrRestartNisd[idx].entry['/0/num-pblks-used'] }}"
         nisd_keys:
              - "/nisd_root_entry/0/num-pblks-used"
              - "/nisd_root_entry/0/num-reserved-pblks-used"
              - "/nisd_chunks/15/vblks-written"
              - "/nisd_chunks/15/vdev-uuid"
              - "/nisd_chunks/15/num-data-pblks"
              - "/nisd_chunks/15/num-meta-pblks"
              - "/nisd_chunks/15/num-reserved-meta-pblks"
         lookout_uuid: "{{ get_lookout[0] }}"
         getNiovaBlockTest: "{{ lookup('niova_ctlrequest', 'lookup', item, nisd_keys, 'nisd', lookout_uuid) }}"
       debug:
         msg: "Verify nisd values after writes: {{ getNiovaBlockTest }}"    
       no_log: false
       until: >
         (getNiovaBlockTest['/0/num-pblks-used'] == ((old_num_block_used | int) + 50)) and
         (getNiovaBlockTest['/0/num-reserved-pblks-used'] == 1) and
         (getNiovaBlockTest['/15/vdev-uuid'] == VdevUUIDS[idx]) and
         (getNiovaBlockTest['/15/num-data-pblks'] == 50) and
         (getNiovaBlockTest['/15/num-meta-pblks'] == 0) and
         (getNiovaBlockTest['/15/num-reserved-meta-pblks'] == 1) and
         (getNiovaBlockTest['/15/vblks-written'] == 1600)
       retries: 10
       delay: 1
       loop: "{{ get_nisd }}"
       loop_control:
         index_var: idx

     - name: "{{ recipe_name }}: Store the metablock-seqno."
       vars:
         stage: "get_metablock_seqno"
         lookout_uuid: "{{ get_lookout[0] }}"
       set_fact:
         oldMetablockSeqNos: >-
           {{
             oldMetablockSeqNos | default([]) +
             [lookup('niova_ctlrequest', 'lookup', item, '/nisd_chunks/15/metablock-seqno', 'nisd', lookout_uuid)['/15/metablock-seqno']]
           }}
       loop: "{{ get_nisd }}"

     - debug:
         msg: "oldMetablockSeqNos: {{ oldMetablockSeqNos  }}"

     - name: "{{ recipe_name }}: Kill the nisd process."
       debug:
         msg:  "{{ lookup('niova_raftprocess', 'kill', item) }}"
       no_log: false
       loop: "{{ get_nisd }}"

     - name: "{{ recipe_name }}: Restart same nisd process."
       vars:
          input_param: {
                  'nisd_uuid' : '{{ item }}',
                  'uport' : '{{ 1053 + (nisd_idx*2) }}',
                  'lookout_uuid': '{{ get_lookout[0] }}'
                  }
       debug:
         msg: "{{ lookup('nisd_handler', 'nisd', input_param) }}"
       no_log: True
       loop: "{{ get_nisd }}"
       loop_control:
         index_var: nisd_idx

     - name: "{{ recipe_name}}: Wait until nisd_root_entry gets updated after second restart."
       vars:
          stage: "wait_for_nisd_root_entry_after_2nd_restart"
          lookout_uuid: "{{ get_lookout[0] }}"
       debug:
         msg: 
          - "Waiting for nisd to get updated"
          - "{{ lookup('niova_ctlrequest', 'lookup', item, '/nisd_root_entry/0/status', 'nisd', lookout_uuid) }}"
       until: lookup('niova_ctlrequest', 'lookup', item, "/nisd_root_entry/0/status", 'nisd', lookout_uuid) | dict2items | map(attribute='value') | list | first == "running"
       retries: 10
       delay: 1
       loop: "{{ get_nisd }}"
 
     # NOTE: This check in the below task has been bypassed for testing in CI. Should be restored once the issue is resolved.
     # (aftrRestart['/0/num-pblks-used'] != (old_num_block_used | int) + 50)
     
     - name: "{{ recipe_name }}: Verify nisd_root_entry after second restart."
       vars:
        stage: "aftr2ndRestart_nisd_info"
        old_num_block_used: "{{ aftrRestartNisd[idx].entry['/0/num-pblks-used'] }}"
        lookout_uuid: "{{ get_lookout[0] }}"
        aftrRestart: "{{ lookup('niova_ctlrequest', 'lookup', item, nisd_root_keys, 'nisd', lookout_uuid) }}"
       debug:
        msg:
          - "Verify nisd_root_entry after second restart for {{ item }}: {{ aftrRestart }}"
          - "old_num_block_used: {{ old_num_block_used }}"
       no_log: false
       failed_when: >
        (aftrRestart['/0/uuid'] != item) or
        (aftrRestart['/0/status'] != "running") or
        (aftrRestart['/0/vblks-written'] != 0) or
        (aftrRestart['/0/num-reserved-pblks-used'] != 1) or
        (aftrRestart['/0/num-pblks-used'] < (old_num_block_used | int) + 50)
       loop: "{{ get_nisd }}"
       loop_control:
        index_var: idx

     - name: "{{ recipe_name }}: Verify nisd_chunks checks after 2nd restart."
       vars:
         stage: "aftr2ndRestart_nisd_chunks"
         old_metablock: "{{ oldMetablockSeqNos[idx] }}"
         lookout_uuid: "{{ get_lookout[0] }}"
         aftrRestart: "{{ lookup('niova_ctlrequest', 'lookup', item, nisd_chunk_keys, 'nisd', lookout_uuid) }}"
       debug:
         msg: "Verify nisd_chunks Checks for {{ item }}: old_metablock={{ old_metablock }}, aftrRestart={{ aftrRestart }}"
       no_log: false
       failed_when: >
         (aftrRestart['/0/vdev-uuid'] != VdevUUIDS[idx]) or
         (aftrRestart['/0/number'] != 0) or
         (aftrRestart['/0/num-data-pblks'] != 50) or
         (aftrRestart['/0/num-meta-pblks'] != 0) or
         (aftrRestart['/0/num-reserved-meta-pblks'] != 1) or
         (aftrRestart['/merge-info/shallow-cnt'] != 0) or
         (aftrRestart['/merge-info/full-status'] != 'idle') or
         (aftrRestart['/0/metablock-seqno'] != (old_metablock | int))
       loop: "{{ get_nisd }}"
       loop_control:
         index_var: idx

     - name: "{{ recipe_name }}: Perform a Read of the Previously Written VBLKS."
       vars:
         input_param: {
                 'enable_auth': 0,
                 'cp_mode': 0,
                 'nisd_uuid_to_write' : 'unix:{{ get_nisd[item] }}',
                 'vdev' : '{{ VdevUUIDS[item] }}',
                 'rd_op_ratio' : '100',
                 'random_seed_pt' : '123',
                 'client_uuid' : '{{ ClientUUIDS[item] }}',
                 'request_size_in_bytes' : '32',
                 'queue_depth' : '1',
                 'num_ops' : '50',
                 'integrity_check' : True,
                 'sequential_writes' : False,
                 'blocking_process' : False,
                 'lookout_uuid': '{{ get_lookout[0] }}'
                 }
       set_fact:
          rd_results: "{{ (rd_results | default([])) + [lookup('nisd_handler', 'niova-block-test', input_param) | string] }}"
       loop: "{{ range(0, get_nisd | length) | list }}"

     - name: "{{ recipe_name }}: Show read results."
       debug:
         msg: "Read results: {{ rd_results }}"

     - name: "{{ recipe_name }}: Fail if any read failed."
       debug:
         msg: "One or more niova-block-test reads failed: {{ rd_results }}"
       failed_when: (rd_results | reject('equalto', '0') | list | length) > 0

     - name: "Verify 'tasks' items are idle."
       include_role:
         name: common
         tasks_from: verify_nisd_tasks_parameters
       vars:
         NisdUUID: "{{ nisd_uuid }}"
         LookoutUUID: "{{ get_lookout[0] }}"
       loop: "{{ get_nisd }}"
       loop_control:
         loop_var: nisd_uuid

     - name: "{{ recipe_name }}: Verify nisd_root_entry."
       vars:
         stage: "aftrRead_nisd_info"
         nisd_keys:
              - "/nisd_root_entry/0/vblks-read"
              - "/nisd_root_entry/0/vblks-hole-read"
         lookout_uuid: "{{ get_lookout[0] }}"
         aftrRead: "{{ lookup('niova_ctlrequest', 'lookup', item, nisd_keys, 'nisd', lookout_uuid) }}"
       debug:
         msg: "Verify nisd_root_entry: {{ aftrRead }}"
       no_log: True
       failed_when: >
         (aftrRead['/0/vblks-read'] != 1600) or
         (aftrRead['/0/vblks-hole-read'] != 0)
       loop: "{{ get_nisd }}"

     - name: "{{ recipe_name }}: Verify nisd_chunk checks."
       vars:
         nisd_keys:
              - "/nisd_chunks/15/vblks-read"
              - "/nisd_chunks/15/num-cme"
              - "/nisd_chunks/15/ref-cnt"
         stage: "aftrRead_nisd_chunk"
         lookout_uuid: "{{ get_lookout[0] }}"
         aftrRead: "{{ lookup('niova_ctlrequest', 'lookup', item, nisd_keys, 'nisd', lookout_uuid) }}"
       debug:
         msg: "Verify nisd_chunks: {{ aftrRead }}"
       no_log: false
       failed_when: >
         (aftrRead['/15/vblks-read'] != 1600) or
         (aftrRead['/15/ref-cnt'] != ((aftrRead['/15/num-cme'] | int) + 1))
       loop: "{{ get_nisd }}"

    rescue:
     - name: "Recipe: {{ recipe_name }} failed"
       set_fact:
         terminate_recipe: true
