
    - name: "{{ recipe_name }}: Get nisd 'tasks' list"
      vars:
        stage: "verify_nisd_tasks_val"
        tasks_keys:
             - "/tasks"
        process_type: "nisd"
        lookout_uuid: "{{ LookoutUUID }}"
      set_fact:
        GetTasksList: "{{ lookup('niova_ctlrequest', 'lookup', NisdUUID, tasks_keys, 'nisd', lookout_uuid) }}"
      no_log: True

    - name: "{{ recipe_name }}: Gather 'tasks' items in the list."
      set_fact:
        TasksList: >-
          {{
            (TasksList | default([]))
            + [
              item['running'] | string,
              item['wait']['co-buf'] | string,
              item['wait']['bulk-buf'] | string,
              item['wait']['io'] | string,
              item['wait']['other'] | string
            ]
          }}
      loop: "{{ GetTasksList['//tasks'] }}"
      no_log: True

    - name: "{{ recipe_name }}: Ensure 'tasks' items are Idle"
      debug:
        msg: "Ensure 'tasks' items are Idle."
      failed_when: item != "0"
      loop: "{{ TasksList }}"
      no_log: True


